### ISSUE TITLE
[heaty] Make the scheduler general purpose

### ISSUE THREAD

**Issue by borpin** [efficiosoft/hass-apps#18]
Enhancement.

I was wondering if you had considered breaking the scheduler out into a separate component?  How you have structured defining schedules and rules really is very elegant and is the only scheduler I have found for HA.

There are other applications for a scheduler so being able to define all such schedules in one place would be a great addition to HA.

Cheers

**Comment by efficiosoft** [comment]
Hi,

In general, I like that idea. However, I can't imagine how to break out the scheduling in a way that's universally applicable to different scenarios. At the moment, the scheduling works out temperature values, incl. the ``Add`` functionality. The result of scheduling has to mean something that can be interpreted. If you have a comprehensive idea how that could look like, please let me know.

Best regards
Robert

**Comment by efficiosoft** [comment]
Another point to consider is that Heaty does way more than calling some services at scheduled times. It handles open window detection, re-sends commands to overcome network outages, re-applies schedules after manual adjustments have been made, calculates statistics and so on.

If the scheduling was separated into a HA component, a lot of redesigning had to be done in order to have it all working together as it should.

In fact, arbitrary services can be called by Heaty right at the moment with a bit of configuration. I do this to control my coffee machine, for instance.

Hence another approach I'm thinking of would be to loose Heaty from heating control at all and define profiles for different things that can be controlled and which can then be applied to rooms. This would require a lot of work too, but it seems more favorable than moving the scheduler to a HA component to me.

**Comment by efficiosoft** [comment]
Will be accomplished by Schedy.
