### ISSUE TITLE
[schedy] Problem with generic actor and short_values

### ISSUE THREAD

**Issue by SebuZet** [efficiosoft/hass-apps#29]
Hi, I've observed strange behavior when device is turned off and Schedy is going to turn it on.
Replication steps:
- device is turned off
- schedy is turning device on
- device is turned on for about 1s
- device is turned off by schedy
- after few seconds device is turned on again by schedy

Problem occurs only when schedy is changing state from Off to On.
Schedy [config](https://github.com/SebuZet/home-assistant-configuration/blob/master/appdeamon/apps/purifier.yaml)
Log [file](https://github.com/SebuZet/home-assistant-configuration/blob/master/log.txt)

**Comment by efficiosoft** [comment]
Hi,

The log looks perfectly ok. Schedy just calls the ``fan.turn_on`` and immediately after that the ``fan.set_speed`` services. What behaves strange is the fan, which first comes on in the ``favorite`` mode (probably because that was the one previously set), then turns off and comes back on in the ``silent`` mode. You could fire the two services manually shortly after each other to verify this also happens without Schedy.

Best regards
Robert

**Comment by efficiosoft** [comment]
You can try using ``call_reversed: true`` in the actor config with latest state from master branch to have the services called in reverse order. That will probably help in some situations like yours.

I'm closing this issue. Feel free to comment further on how it goes.

**Comment by SebuZet** [comment]
Hi, 
Thanks for checking this for me.
Generaly it works. Strange behaviour can be observed only when device is switched on. 
It can be device specific behaviour. I noticed, that turning my purifier on can be achieved by setting speed mode. If device was powered off then it will be switched on automatiacaly. 
Thanks once again.

**Comment by efficiosoft** [comment]
But then you should really use call_reversed to have it fixed.
