### ISSUE TITLE
Unsupported characters in log messages

### ISSUE THREAD

**Issue by chbndrhnns** [efficiosoft/hass-apps#46]
I view the Appdaemon logs via its Hass add on.

There, the log messages look like that:

<img width="1223" alt="Screenshot 2020-01-28 at 16 32 43" src="https://user-images.githubusercontent.com/7534547/73278585-15ad7d00-41ec-11ea-9d36-171dcba66d16.png">

**Comment by efficiosoft** [comment]
Hi,

Thanks for reporting.

Could you describe where exactly in which log message you see unsupported characters? I'm blind and thus can't see what that image shows.

Best regards
Robert

**Comment by chbndrhnns** [comment]
The characters appear in the appdaemon logs when I view them via the browser.

The strange characters appear twice after the reported temperature.

I am copying one line of logs here for you:

```
2020-02-05 08:57:12.733880 INFO schedy_heating: --> [R:kueche] [A:climate.kuche] Received value of 7.0��.

```

**Comment by efficiosoft** [comment]
Hm, this should simply be a ° sign... It is set correctly in the sources, I can just imagine that the log viewer (or some other component along the way) doesn't support UTF-8 or isn't configured properly.

If you place another UTF-8 character somewhere, e.g. a "ä" in a room's `friendly_name` name, does this appear messed up as well?

**Comment by efficiosoft** [comment]
I checked with my own installation running the AppDaemon docker image, and non-ASCII characters aren't displayed correctly there either, so I guess it's an issue with how AppDaemon prints the log messages. You can verify this yourself by creating an own app and letting it log something with umlauts.

I'm closing this issue since it's not related to Schedy directly but will report it to AppDaemon when I've got more time.

Best regards
Robert
